platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CMHealth_Example' do
  pod 'CMHealth', :path => '../'
  pod 'CareKit', :path => '../../CareKit-1.2'
  pod 'CloudMine', :path => '../../cloudmine-ios'
  #pod 'CareKit', :path => '../../carekit-20-beta-4.5'
  #pod 'CareKit', :path => '../../carekit-internal-beta-3'
  #pod 'CareKit', :path => '../../carekit-internal-20'
  #pod 'CareKit', :path => '../../carekit-beta-private'
  #pod "CareKit", "~> 1.0"

  target 'CMHealth_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
