platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CMHealth_Example' do
  pod 'CMHealth', :path => '../'
  pod 'CareKit', :path => '../../carekit-beta-private'
  #pod "CareKit", "~> 1.0"

  target 'CMHealth_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
