#import <CloudMine/CMObject.h>
#import <ResearchKit/ResearchKit.h>

/** The function type of the completion block executed after signature image is fetched.
 */
typedef void(^CMHFetchSignatureCompletion)(UIImage *_Nullable signature, NSError *_Nullable error);

/**
 * `CMHConsent` is a subclass of `CMObject`. It provides access to the participant consent result 
 *  for any given study that has previously been uploaded.
 *
 *  @see CMHUser class -uploadUserConsent:forStudyWithDescriptor:andCompletion:
 *  @see CMHUser class -fetchUserConsentForStudyWithDescriptor:andCompletion:
 *  
 *  ///--------------------------
 *  /// @name Instantiation
 *  ///--------------------------
 *
 *  Developers should never instantiate CMHConsent directly.
 * 
 *  ///--------------------------
 *  /// @name Subclassing
 *  ///--------------------------
 * 
 *  Developers should never subclass CMHConsent.
 *
 *
 */
@interface CMHConsent : CMObject

/**
 *  The `ORKTaskResult` containing the consent step the particpant completed.
 *
 *  @warning This property will **not** contain the signature image in the results hiearchy.
 *
 *  @see -fetchSignatureImageWithCompletion:
 */
@property (nonatomic, nullable, readonly) ORKTaskResult *consentResult;

/**
 *  The descriptor of the study for which the particpant was consenting.
 */
@property (nonatomic, nullable, readonly) NSString *studyDescriptor;

/**
 * Executes a network request to fetch the signature image generated by the
 * user when the completed the consent stored by this instance.
 *
 * @param block Executed when the request to fetch the image returns successfully or fails.
 */
- (void)fetchSignatureImageWithCompletion:(_Nullable CMHFetchSignatureCompletion)block;

@end
