#import <CloudMine/CMObject.h>
#import <ResearchKit/ResearchKit.h>

typedef void(^CMHUploadPDFCompletion)(NSError *_Nullable error);
typedef void(^CMHFetchConsentPDFCompletion)(NSData *_Nullable pdfData, NSError *_Nullable error);
typedef void(^CMHFetchSignatureCompletion)(UIImage *_Nullable signature, NSError *_Nullable error);

/**
 *  `CMHConsent` is a subclass of `CMObject`. It provides access to the participant consent
 *  result for any given study that has previously been uploaded.
 *  Developers should never instantiate CMHConsent directly. Developers should never 
 *  subclass `CMHConsent`.
 *
 *  @see CMHUser class -uploadUserConsent:forStudyWithDescriptor:andCompletion:
 *  @see CMHUser class -fetchUserConsentForStudyWithDescriptor:andCompletion:
 *
 */
@interface CMHConsent : CMObject

/**
 *  The `ORKTaskResult` containing the consent step the particpant completed.
 *
 *  @warning This property will **not** contain the signature image in the results hiearchy
 *  when fetched from the backend
 *
 *  @see -fetchSignatureImageWithCompletion:
 */
@property (nonatomic, nullable, readonly) ORKTaskResult *consentResult;

/**
 *  The descriptor of the study for which the particpant was consenting.
 */
@property (nonatomic, nullable, readonly) NSString *studyDescriptor;

/**
 *  Executes a network request to upload the consent PDF document associated
 *  with this consent object. Generally, this would be generated by the
 *  `–makePDFWithCompletionHandler:` method on `ORKConsentDocument`.
 *
 *  @see -fetchConsentPDFWithCompletion:
 *
 *  @param pdfData Data of consent PDF associated with this object
 *  @param block Executed when the upload request returns successfully or fails with an error
 */
- (void)uploadConsentPDF:(NSData *_Nonnull)pdfData withCompletion:(_Nullable CMHUploadPDFCompletion)block;

/**
 *  Executes a network request to fetch the consent PDF data of 
 *  previously uploaded and associated with this consent object.
 *
 *  @see -uploadConsentPDF:withCompletion:
 *
 *  @param block Exectued when the request to fetch the PDF returns successfully 
 *  or fails with an error
 */
- (void)fetchConsentPDFWithCompletion:(_Nullable CMHFetchConsentPDFCompletion)block;

/**
 *  Executes a network request to fetch the signature image generated by the
 *  user when the completed the consent stored by this instance.
 *
 *  @param block Executed when the request to fetch the image returns successfully or fails
 *  with an error
 */
- (void)fetchSignatureImageWithCompletion:(_Nullable CMHFetchSignatureCompletion)block;

@end
